version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    steps:
      - checkout
      - run:
          name: run tests
          command: docker-compose run --rm lorawan make test

